exports.DB_ERROR = 1;
exports.DB_ERROR_MESSAGE = 'DATABASE ERROR'

exports.MISSION_NOT_FOUND = 2;
exports.MISSION_NOT_FOUND_MESSAGE = 'MISSION NOT FOUND';

exports.VIDEO_FINISHED = 3;
exports.VIDEO_FINISHED_MESSAGE = 'VIDEO FINISHED'



